export { default as UserHome } from './UserHome/UserHome';
export { default as UserNav } from './UserNav/UserNav';
export { default as LoginForm } from './LoginForm/LoginForm'
export { default as LoginNav } from './LoginNav/Loginnav'
export { default as SingupForm } from './Singup/SingupForm'
export { default as AdminSingup } from './AdminLogin/AdminLogin'
export { default as AdminNav } from './AdminNav/AdminNav'
export { default as DetailsOfUser } from './DetailsOfUser/DetailsOfUser'
export { default as AdminEditUser } from './AdminEditForm/AdminEditForm'